#描述/签名
name: "Yan ziJun's blog"
description: "阎子君 | study"

# 博客logo图片URL，建议尺寸不超过300px × 300px
avatar: https://yan-zijun.github.io/images/zijun.jpg
# favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://yan-zijun.github.io/images/zijun.ico

# 网站域名
url: blog.zijun.us.kg

# 菜单中的按钮
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags

# 每页的文章数
paginate: 4
# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 社交网络链接
footer-links:
  weibo:  #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: 3239577894@qq.com
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: #Yan-ziJun
  instagram: #https://instagram.com/<>
  linkedin: #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: #yanzijun
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: # https://www.twitter.com/<your_twitter_username> 
  youtube: # channel/<your_long_string> or user/<user-name>

# 站点页脚的文字
footer-text: Copyright (c) 2024 yanzijun

# 输入Disqus shortname，即可添加评论区，请查阅文档，设置自己的disqus站点，不要继续使用我的站点loffer
disqus: # fromendworld

#评论
# Gitalk
gitalk:
  clientID: Ov23liYzUswY3hGZwcr9
  clientSecret: 3c500587ddec4c9dd5a9f83c6df465dce5a9985d
  repo: yan-zijun.github.io
  owner: yanzijun

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-KR4PBY7HKS



# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: 


#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

